### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vandres** [fr34q/NineMensMorris#3]
Hi, which is the License for the code?

**Comment by fr34q** [comment]
Hi!
I added a license file (MIT), thanks for the request.
I would be pleased to see what you made out of it, so feel free to get back to me.

**Comment by vandres** [comment]
Thank you very much. At the moment I am still evaluating for a project and I really like the fact you used TypeScript. I will come back top you, if the project starts. Then I would add network code to play over the internet :)
